language: node_js
matrix:
 include:
  - node_js: "stable"
    env: GULP_TASK="run1"
  - node_js: "stable"
    env: GULP_TASK="run2"
 fast_finish: true

notifications:
  email: false
addons:
  browserstack:
    username:
      secure: G29ddSiavzYyC7t3XVvmBkNBkpEhfIjKdLu89Gx611xuEeT8B37BeZorJWi3Cf+8DrRH0kz/gyQHxxgK2GIpotCPkSwZmzRVr9RrGeJo45oSTWxQveF6Rj65iijRQaFhvUTq6Z4YUCqo2xPDwK+Y3Vweuu1nA+tPDRykH0L2lL6VxzTmvoPtIP01+ZRcnqAd5NfBJbwznjcE8ntubsBC7pDm/4pg+bu8170tnC9GdTaCHTgz7dz7KMV0RG+xvqEsopbZWRT0Mi2C1ZKJHo6OQ3WNC1oOyejB3B08nxUI+SP7VqSVR+HP7ETnTZWbRIFUmVf16Z+1t+aVnOpNnFRzwcALkrdUuht85kmVtsAMtFUVNOpp1z27SK1/46hZWdlW+RsvSjG7OtBCxqYX8sHU9ixnd+xpFrNknm+YaBnsZl2D4hkqQ97mcMW9sgog8/e8EX32+qol+AR1hBKtS0jKo9ejzNuop4EfNc8hGikOOc1ZuG1REIBTRpIhCsooaFCMpDRVRMXcq6ewUJbzGjtRkfxDuNlBtqzgQOhmaVJC9P+7eR2PXtrTaJ+XqrkFdyu8I6TvGmQVqvl0RRq8rlX3AsnVbOhqS5PsoTcsuK3RLc/DcgiPGTKKiY/xy+Pnn9TCzKl5L9NTKI8a8ElwMtDupEWx3ZbUXZnfHtMOxkDxs1k=
    access_key: 
      secure: ck6ojOiJWodIBpKXXleXeSsVKJnefLxXW451o5gOFki+f4ncbcaEIWTKIIkm2ROZa4I76WyLIjXwvnu0z5bTKQlwPcKWxfWiPnb/g0gVWUX1xmhfiheFAro5JmN61Jugh4Dh4y6B5ImWvnoVeLBUgUrdgHKx1j3rM74aKeSDsXlHDVJcapwpW8TqMf0rQp/6RYc0io3egQPwCIc8ZYxKb1fbcvmsFEYEQ0eSDjroG69TzcrEPQ0NxbXXCvfxrnULhHFadV68OBXlHcSCdUZyYRodniSZiD2q/wgO8CFx5WwAyFzYxZL6qaUNFGXaL5MtCkVvtr3R9gCsjWxtToLw+vSRRM/N3J752UmaXNEycP1no+svWW3hvOdfQeIenLF1TF/0xAT4KgSqBpRLkBM1TNkU6nnSh1zE+QGrZU4hEWDzC4yx1MjbcZbaMKkCDpNCxf3dDpp/vCmoCZLqaebadvSZEcSZSrx5N6aRUto7mSUQfwOG0l21XA5kQncVDb0LP7mnu1g8zr/ZJ50gC7T0DBq5xS2tPqXJciLF7lV88UEOob1JIu5csdba1RGXmk7qMloOMxp3ohGG1PGq0G/56EiW3ydVvWZd21rexMpIDNG0KvSnv+hkr+Ev2Uw8mHXlEAxvlTM5lcd7dhp/cyVzl3aSwTYTCEdodm2gj5Sx5Hs=